{
 "title": "Allure autotest statistics",
 "tags": [ "allure" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project",
    "label": "Project name",
    "query": "SELECT distinct project  FROM test_results LIMIT 1000"
   },
   {
    "name": "Status",
    "label": "Test status",
    "query": "SELECT \n    distinct status\nFROM test_results"
   },
   {
    "name": "Tag",
    "label": "Allure tag",
    "query": "SELECT \n    distinct arrayJoin(labels).2 as tag_value\nFROM test_results\nWHERE arrayJoin(labels).1 = 'tag'"
   },
   { "name": "Datasource", "label": "Datasource", "query": "grafana-clickhouse-datasource" },
   {
    "name": "Host",
    "label": "Host",
    "query": "SELECT \n    distinct arrayJoin(labels).2 as tag_value\nFROM test_results\nWHERE arrayJoin(labels).1 = 'host'"
   },
   { "name": "TZ", "label": "TZ", "query": "Europe/Moscow" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Total statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of executed tests by status",
   "type": "bargauge",
   "description": "Detail information with tests statistic",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    COUNT(*) AS total,\r\n    COUNTIf(status = 'passed') AS passed,\r\n    COUNTIf(status = 'failed') AS failed,\r\n    COUNTIf(status = 'broken') AS broken,\r\n    COUNTIf(status = 'skipped') AS skipped,\r\n    COUNTIf(status = 'unknown') AS unknown\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime)"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "piechart",
   "description": "Project status rate information",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    round(countIf(status = 'passed') * 100.0 / count(), 2) as passed,\r\n    round(countIf(status = 'failed') * 100.0 / count(), 2) as failed,\r\n    round(countIf(status = 'broken') * 100.0 / count(), 2) as broken,\r\n    round(countIf(status = 'skipped') * 100.0 / count(), 2) as skipped,\r\n    round(countIf(status = 'unknown') * 100.0 / count(), 2) as unknown\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime)"
    }
   ]
  },
  {
   "title": "Projects pass rate",
   "type": "barchart",
   "description": "Percent of success tests",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    round(countIf(status = 'passed') * 100.0 / count(), 2) as passed,\r\n    project\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime)\r\ngroup by project\r\norder by passed desc\r\n"
    }
   ]
  },
  {
   "title": "Number of executed tests",
   "type": "bargauge",
   "description": "Number of executed tests of each project",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT count(*) as test_count,project \r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime)\r\ngroup by project\r\nORDER BY test_count DESC"
    }
   ]
  },
  {
   "title": "Avg test duration in sec",
   "type": "bargauge",
   "description": "Average tests duration by each project",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    project,\r\n    avg((stop - start) / 1000) as duration_avg_sec\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime)\r\nGROUP BY project\r\nORDER BY duration_avg_sec DESC"
    }
   ]
  },
  {
   "title": "Running tests history",
   "type": "timeseries",
   "description": "Count of all tests that was running",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH expanded AS\r\n(\r\n    SELECT\r\n        project,\r\n        arrayJoin(\r\n            range(\r\n                toUInt32(start / 1000),\r\n                toUInt32(stop  / 1000)\r\n            )\r\n        ) AS time_sec\r\n    FROM test_results\r\n    WHERE\r\n        start <= $__to\r\n        AND stop  >= $__from\r\n)\r\nSELECT\r\n    time,\r\n    metric,\r\n    running_tests\r\nFROM\r\n(\r\n    SELECT\r\n        toDateTime64(time_sec, 3) AS time,\r\n        project AS metric,\r\n        count(*) AS running_tests\r\n    FROM expanded\r\n    WHERE\r\n        time_sec >= toUnixTimestamp($__from / 1000)\r\n        AND time_sec <= toUnixTimestamp($__to   / 1000)\r\n    GROUP BY\r\n        time,\r\n        metric\r\n\r\n    UNION ALL\r\n\r\n    SELECT\r\n        toDateTime64(time_sec, 3) AS time,\r\n        'TOTAL TESTS' AS metric,\r\n        count(*) AS running_tests\r\n    FROM expanded\r\n    WHERE\r\n        time_sec >= toUnixTimestamp($__from / 1000)\r\n        AND time_sec <= toUnixTimestamp($__to / 1000)\r\n    GROUP BY\r\n        time\r\n)\r\nORDER BY time, metric;"
    }
   ]
  },
  {
   "title": "Tests duration in seconds",
   "type": "timeseries",
   "description": "Tests duration trend in seconds ",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    stop_datetime AS time,\r\n    project,\r\n    toString(upload_time, '$TZ') AS upload_time,\r\n    (stop - start) / 1000 AS duration_sec\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime)\r\nORDER BY time, upload_time"
    }
   ]
  },
  {
   "title": "Upload tests count history",
   "type": "timeseries",
   "description": "History of all tests that was uploaded ",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    upload_time,\r\n    project,\r\n    count(*) AS count\r\nFROM test_results\r\nGROUP BY upload_time, project\r\nORDER BY upload_time"
    }
   ]
  },
  {
   "title": "$Project statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "repeat": "Project",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of tests executed with status",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n    COUNT(*) AS total,\r\n    COUNTIf(status = 'passed') AS passed,\r\n    COUNTIf(status = 'failed') AS failed,\r\n    COUNTIf(status = 'broken') AS broken,\r\n    COUNTIf(status = 'skipped') AS skipped,\r\n    COUNTIf(status = 'unknown') AS unknown\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime) AND project='${Project}'"
      }
     ]
    },
    {
     "title": "$Project rate",
     "type": "piechart",
     "description": "Project status rate information",
     "gridPos": { "h": 10, "w": 5, "x": 9, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n    round(countIf(status = 'passed') * 100.0 / count(), 2) as passed,\r\n    round(countIf(status = 'failed') * 100.0 / count(), 2) as failed,\r\n    round(countIf(status = 'broken') * 100.0 / count(), 2) as broken,\r\n    round(countIf(status = 'skipped') * 100.0 / count(), 2) as skipped,\r\n    round(countIf(status = 'unknown') * 100.0 / count(), 2) as unknown\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime) AND project ='${Project}'"
      }
     ]
    },
    {
     "title": "Avg test duration in seconds",
     "type": "stat",
     "description": "Average test duration in seconds",
     "gridPos": { "h": 10, "w": 5, "x": 14, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n    avg((stop - start) / 1000) as duration_avg_sec\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime) AND project = '${Project}'"
      }
     ]
    },
    {
     "title": "Upload tests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 63 },
     "targets": [
      {
       "rawSql": "WITH test_stats AS (\r\n    SELECT \r\n        upload_time,\r\n        countIf(status = 'passed') AS passed,\r\n        countIf(status = 'failed') AS failed,\r\n        countIf(status = 'broken') AS broken,\r\n        countIf(status = 'skipped') AS skipped,\r\n        countIf(status = 'unknown') AS unknown,\r\n        count(*) AS total\r\n    FROM test_results\r\n    where project = '${Project}'\r\n    GROUP BY upload_time\r\n)\r\nSELECT \r\n    upload_time,\r\n    passed,\r\n    failed,\r\n    broken,\r\n    skipped, \r\n    unknown,\r\n    total\r\nFROM test_stats\r\nORDER BY upload_time;"
      }
     ]
    },
    {
     "title": "Rate by ${Tag}",
     "type": "piechart",
     "description": "Project status rate information",
     "gridPos": { "h": 10, "w": 5, "x": 14, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n    round(countIf(status = 'passed') * 100.0 / count(), 2) as passed,\r\n    round(countIf(status = 'failed') * 100.0 / count(), 2) as failed,\r\n    round(countIf(status = 'broken') * 100.0 / count(), 2) as broken,\r\n    round(countIf(status = 'skipped') * 100.0 / count(), 2) as skipped,\r\n    round(countIf(status = 'unknown') * 100.0 / count(), 2) as unknown\r\nFROM test_results\r\nWHERE project ='${Project}' AND\r\n$__timeFilter(stop_datetime) AND\r\nhasAll(label_tag,[${Tag}])"
      }
     ]
    },
    {
     "title": "Running tests history",
     "type": "timeseries",
     "description": "Count of all tests that was running",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 73 },
     "targets": [
      {
       "rawSql": "WITH expanded AS\r\n(\r\n    SELECT\r\n        project,\r\n        arrayJoin(\r\n            range(\r\n                toUInt32(start / 1000),\r\n                toUInt32(stop  / 1000)\r\n            )\r\n        ) AS time_sec\r\n    FROM test_results\r\n    WHERE\r\n        start <= $__to\r\n        AND stop  >= $__from\r\n        AND project = '$Project'\r\n)\r\nSELECT\r\n    time,\r\n    metric,\r\n    running_tests\r\nFROM\r\n(\r\n    SELECT\r\n        toDateTime64(time_sec, 3) AS time,\r\n        project AS metric,\r\n        count(*) AS running_tests\r\n    FROM expanded\r\n    WHERE\r\n        time_sec >= toUnixTimestamp($__from / 1000)\r\n        AND time_sec <= toUnixTimestamp($__to   / 1000)\r\n    GROUP BY\r\n        time,\r\n        metric\r\n)\r\nORDER BY time, metric;"
      }
     ]
    },
    {
     "title": "Number of tests executed",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 14, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n    count(*) as count\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime) AND project ='${Project}'"
      }
     ]
    },
    {
     "title": "Tests second duration in $Project ",
     "type": "timeseries",
     "description": "Tests second duration trend",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 83 },
     "targets": [
      {
       "rawSql": "SELECT\r\n    stop_datetime AS time,\r\n    project,\r\n    toString(upload_time, '$TZ') AS upload_time,\r\n    (stop - start) / 1000 AS duration_sec\r\nFROM test_results\r\nWHERE $__timeFilter(stop_datetime) AND project = '$Project'\r\nORDER BY time, upload_time"
      }
     ]
    },
    {
     "title": "Top 10 $Status tests",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 93 },
     "targets": [
      {
       "rawSql": "SELECT \r\ncount(*) as count, \r\ntestCaseName \r\nFROM test_results \r\nwhere status = '$Status' and project = '$Project' and $__timeFilter(stop_datetime)\r\ngroup by testCaseName \r\norder by count \r\ndesc limit 10"
      }
     ]
    },
    {
     "title": "$Project test results details",
     "type": "logs",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 103 },
     "targets": [
      {
       "rawSql": "SELECT \r\n    toDateTime64(start/1000, 3) as time, \r\n    testCaseName as metric,\r\n    status,\r\n    toString(fromUnixTimestamp64Milli(start),'$TZ') as startDate,\r\n    toString(fromUnixTimestamp64Milli(stop),'$TZ') as stopDate,\r\n    statusDetails,\r\n    (stop - start) / 1000 as duration_sec,\r\n    CASE \r\n        WHEN status = 'passed' THEN 'info'\r\n        WHEN status = 'failed' THEN 'error'\r\n        WHEN status = 'broken' THEN 'warning'\r\n        ELSE 'unknown'\r\n    END as level\r\nFROM test_results \r\nWHERE\r\n    project = '$Project' AND \r\n    $__timeFilter(stop_datetime)\r\nORDER BY start ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "$Host statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running tests history on $Host",
     "type": "timeseries",
     "description": "Count of all tests that was running on certain host",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 112 },
     "targets": [
      {
       "rawSql": "WITH expanded AS\r\n(\r\n    SELECT\r\n        project,\r\n        arrayJoin(\r\n            range(\r\n                toUInt32(start / 1000),\r\n                toUInt32(stop  / 1000)\r\n            )\r\n        ) AS time_sec\r\n    FROM test_results\r\n    WHERE\r\n        start <= $__to\r\n        AND stop  >= $__from\r\n        AND label_host = '$Host'\r\n)\r\nSELECT\r\n    time,\r\n    metric,\r\n    running_tests\r\nFROM\r\n(\r\n    SELECT\r\n        toDateTime64(time_sec, 3) AS time,\r\n        project AS metric,\r\n        count(*) AS running_tests\r\n    FROM expanded\r\n    WHERE\r\n        time_sec >= toUnixTimestamp($__from / 1000)\r\n        AND time_sec <= toUnixTimestamp($__to   / 1000)\r\n    GROUP BY\r\n        time,\r\n        metric\r\n\r\n    UNION ALL\r\n\r\n    SELECT\r\n        toDateTime64(time_sec, 3) AS time,\r\n        'TOTAL TESTS' AS metric,\r\n        count(*) AS running_tests\r\n    FROM expanded\r\n    WHERE\r\n        time_sec >= toUnixTimestamp($__from / 1000)\r\n        AND time_sec <= toUnixTimestamp($__to / 1000)\r\n    GROUP BY\r\n        time\r\n)\r\nORDER BY time, metric;"
      }
     ]
    },
    {
     "title": "Tests duration in seconds",
     "type": "timeseries",
     "description": "Tests duration trend in seconds ",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 123 },
     "targets": [
      {
       "rawSql": "SELECT\r\n    stop_datetime AS time,\r\n    project,\r\n    toString(upload_time, '$TZ') AS upload_time,\r\n    (stop - start) / 1000 AS duration_sec\r\nFROM test_results\r\nWHERE label_host = '$Host' AND $__timeFilter(stop_datetime)\r\nORDER BY time, upload_time"
      }
     ]
    }
   ]
  }
 ]
}